user: openproject
group: openproject
targets:
  debian-9: &debian9
    build_dependencies:
      - libsqlite3-dev
    dependencies:
      - unzip
      - poppler-utils
      - unrtf
      - tesseract-ocr
      - catdoc
      - imagemagick
  debian-10:
    <<: *debian9
  ubuntu-16.04:
    <<: *debian9
  ubuntu-18.04:
    <<: *debian9
  ubuntu-20.04:
    <<: *debian9
  centos-8:
    dependencies:
      - unzip
      - epel-release
      - ImageMagick
  centos-7:
   dependencies:
      - epel-release
      - ImageMagick
  sles-12:
    build_dependencies:
      - sqlite3-devel
      - ImageMagick
before_precompile: "packaging/setup"
after_precompile: "packaging/teardown"
services:
  - postgres
installer: https://github.com/pkgr/installer.git
wizards:
  - https://github.com/pkgr/addon-legacy-installer.git
  - https://github.com/opf/addon-openproject-edition.git
  - https://github.com/pkgr/addon-postgres
  - https://github.com/pkgr/addon-apache2.git
  - https://github.com/opf/addon-repositories.git
  - https://github.com/pkgr/addon-smtp.git
  - https://github.com/pkgr/addon-memcached.git
  - https://github.com/opf/addon-openproject.git
buildpack: https://github.com/opf/heroku-buildpack-multi.git
